message: Hello Local

---
spring:
  profiles: local

eureka:
  client:
    enabled: false

---
spring:
  profiles: docker
  cloud:
    config:
      uri: http://ef-ref-config-service:8080
      fail-fast: true